services:
  - type: web
    name: dream-deco-api
    env: node
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: "*"
